//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public int IDHoaDon { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
        public Nullable<int> IDPhong { get; set; }
        public Nullable<int> TongTien { get; set; }
        public string MoTa { get; set; }
        public string HoTenKhach { get; set; }
        public Nullable<int> IDDatPhong { get; set; }
        public string SDT { get; set; }
    
        public virtual tblDatPhong tblDatPhong { get; set; }
        public virtual tblPhong tblPhong { get; set; }
    }
}
