//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLKS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblDatPhong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblDatPhong()
        {
            this.HoaDons = new HashSet<HoaDon>();
        }
    
        public int IDDatPhong { get; set; }
        public Nullable<System.DateTime> ThoiGianBatDau { get; set; }
        public Nullable<System.DateTime> ThoiGianKetThuc { get; set; }
        public Nullable<int> IDPhong { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> TongTien { get; set; }
        public Nullable<int> TienDaCoc { get; set; }
        public Nullable<int> IDTrangThaiDat { get; set; }
        public string TenKhachHang { get; set; }
        public string SDT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual tblPhong tblPhong { get; set; }
        public virtual tblTrangThaiDat tblTrangThaiDat { get; set; }
    }
}
