//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiOnlineMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiThi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaiThi()
        {
            this.BaiThi_DapAn = new HashSet<BaiThi_DapAn>();
        }
    
        public int IDBaiThi { get; set; }
        public Nullable<int> IDCaThi { get; set; }
        public Nullable<int> IDNguoiDung { get; set; }
        public Nullable<int> SoCauDung { get; set; }
        public Nullable<int> TongSoCau { get; set; }
        public Nullable<int> IDDeThi { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> ThoiGianDangNhap { get; set; }
        public Nullable<System.DateTime> ThoiGianNopBai { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiThi_DapAn> BaiThi_DapAn { get; set; }
        public virtual KyThi KyThi { get; set; }
        public virtual DeThi DeThi { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
    }
}
