//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiOnlineMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiThi_DapAn
    {
        public int IDBaiThi { get; set; }
        public int IDCauHoi { get; set; }
        public string TraLoi { get; set; }
        public string DapAn { get; set; }
        public string MoTa { get; set; }
    
        public virtual BaiThi BaiThi { get; set; }
        public virtual CauHoi CauHoi { get; set; }
    }
}
