//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiOnlineMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHoi
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CauHoi()
        {
            this.BaiThi_DapAn = new HashSet<BaiThi_DapAn>();
            this.DeThi_CauHoi = new HashSet<DeThi_CauHoi>();
        }
    
        public int IDCauHoi { get; set; }
        public string TenCauHoi { get; set; }
        public string MoTa { get; set; }
        public string DapAn { get; set; }
        public string TracNghiemA { get; set; }
        public string TracNghiemB { get; set; }
        public string TracNghiemC { get; set; }
        public string TracNghiemD { get; set; }
        public Nullable<int> IDDoanVan { get; set; }
        public Nullable<int> IDDoKho { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BaiThi_DapAn> BaiThi_DapAn { get; set; }
        public virtual DoanVan DoanVan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeThi_CauHoi> DeThi_CauHoi { get; set; }
        public virtual DoKho DoKho { get; set; }
    }
}
