//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThiOnlineMVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeThi_CauHoi
    {
        public int IDDeThi { get; set; }
        public int IDCauHoi { get; set; }
        public string MoTa { get; set; }
    
        public virtual CauHoi CauHoi { get; set; }
        public virtual DeThi DeThi { get; set; }
    }
}
