//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfQLSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class DichVu_SanPham
    {
        public int IDDichVu { get; set; }
        public int IDSanPham { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public string DonViTinh { get; set; }
    
        public virtual DichVu DichVu { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
