//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfQLSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichLieuTrinh
    {
        public int IDLichLieuTrinh { get; set; }
        public Nullable<int> IDLieuTrinh { get; set; }
        public Nullable<System.DateTime> ThoiGianDieuTri { get; set; }
        public Nullable<System.DateTime> ThoiGianBaoTruoc { get; set; }
        public string MoTa { get; set; }
        public Nullable<bool> DaThucHien { get; set; }
    
        public virtual LieuTrinh LieuTrinh { get; set; }
    }
}
