//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfQLSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichHen
    {
        public int IDLichHen { get; set; }
        public string IDKhachHang { get; set; }
        public Nullable<System.DateTime> ThoiGianHen { get; set; }
        public Nullable<System.DateTime> ThoiGianBaoTruoc { get; set; }
        public string NoiDung { get; set; }
        public Nullable<int> IDTrangThaiHen { get; set; }
    
        public virtual TrangThaiHen TrangThaiHen { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
