//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfQLSpa
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.DichVu_SanPham = new HashSet<DichVu_SanPham>();
        }
    
        public int IDSanPham { get; set; }
        public string TenSanPham { get; set; }
        public string DonVi { get; set; }
        public Nullable<int> DonGia { get; set; }
        public string MoTa { get; set; }
        public string UrlAnh { get; set; }
        public Nullable<int> IDHangSanXuat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DichVu_SanPham> DichVu_SanPham { get; set; }
        public virtual HangSanXuat HangSanXuat { get; set; }
    }
}
