//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBDX
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLBaiDoXeEntities : DbContext
    {
        public QLBaiDoXeEntities()
            : base("name=QLBaiDoXeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<HoaDon> HoaDons { get; set; }
        public virtual DbSet<LoaiThe> LoaiThes { get; set; }
        public virtual DbSet<LoaiXe> LoaiXes { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<NhatKyRa> NhatKyRas { get; set; }
        public virtual DbSet<NhatKyVao> NhatKyVaos { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TheGuiXe> TheGuiXes { get; set; }
        public virtual DbSet<XeThang> XeThangs { get; set; }
        public virtual DbSet<XeTrongBai> XeTrongBais { get; set; }
        public virtual DbSet<Quyen> Quyens { get; set; }
    }
}
