//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeThang
    {
        public int IDTheGuiXe { get; set; }
        public string BienSo { get; set; }
        public Nullable<System.DateTime> NgayDangKy { get; set; }
        public Nullable<System.DateTime> NgayHetHan { get; set; }
        public string UrlAnh { get; set; }
        public string MoTa { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual TheGuiXe TheGuiXe { get; set; }
    }
}
