//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLBDX
{
    using System;
    using System.Collections.Generic;
    
    public partial class XeTrongBai
    {
        public string IDXeTrongBai { get; set; }
        public Nullable<System.DateTime> ThoiGianVao { get; set; }
        public Nullable<System.DateTime> ThoiGianRa { get; set; }
        public Nullable<int> IDTheGuiXe { get; set; }
        public Nullable<int> IDLoaiXe { get; set; }
        public string UrlAnh { get; set; }
    
        public virtual LoaiXe LoaiXe { get; set; }
        public virtual TheGuiXe TheGuiXe { get; set; }
    }
}
